#!/bin/sh

# nixos nixpkgs <subcmd>
if [ "$1" == "nixpkgs" ]; then

  if [ "$2" == "dir" ]; then
    nix-instantiate --find-file nixpkgs

  else
    echo "Valid subcommands:"
    echo "  nixos nixpkgs dir"
    exit 1
  fi

# nixos search <query>
elif [ "$1" == "search" ]; then
  nix-env -qaP --description $2

# nixos system <subcmd>
elif [ "$1" == "system" ]; then

  if [ "$2" == "generations" ]; then
    sudo nix-env -p /nix/var/nix/profiles/system --list-generations

  elif [ "$2" == "packages" ]; then
    nix-store -q --references /var/run/current-system/sw | cut -d'-' -f2-

  else
    echo "Valid subcommands:"
    echo "  nixos system generations"
    echo "  nixos system packages"
    exit 1
  fi

# unrecognized
else
  echo "Available subcommands:"
  echo "  nixos nixpkgs dir"
  echo "  nixos search <query>"
  echo "  nixos system <subcommand>"
  exit 1
fi

exit 0
